#! /bin/bash

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <host>"
fi

host=$1
user=core

scp "${@:2}" docker-tcp.socket $user@$host:docker-tcp.socket

ssh -l $user "${@:2}" $host "
sudo mv docker-tcp.socket /etc/systemd/system/docker-tcp.socket
sudo systemctl daemon-reload
sudo systemctl stop docker
sudo systemctl start docker-tcp.socket
sudo systemctl start docker
"
