#! /bin/bash

if [ "$#" -lt 1 ]; then
    script=$0
    echo "Usage: ${script:2} host file ..."
    exit;
fi

if [ "$#" -lt 2 ]; then
    echo "No files given, exiting."
    exit
fi

host=$1
files="${@:2}"

scp -F ~/.ssh/config $files $host:~/

dest=/etc/systemd/system/
cmd=""
for file in $files; do
    cmd="$cmd
sudo mv $file $dest
sudo systemctl enable $dest$file
sudo systemctl start $file"
done;

echo "Starting services (this may take a minute)"
ssh -l core $host "$cmd"
